app:
  env: "local"
  name: "subs service"

http_server:
  host: "0.0.0.0"
  port: 3001

postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "example"
  db_name: "postgres"
  ssl_mode: "disable"