app:
  env: "local"
  migrationsPath: "migrations"

http_server:
  address: "0.0.0.0:8082"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "example"
  db_name: "postgres"
  ssl_mode: "disable"