basePath: /
host: localhost:3001
info:
  contact: {}
  description: This is a sample swagger for subscription service API
  title: Subscription Service API
  version: "1.0"
paths:
  /ping:
    get:
      description: Возвращает pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Пинг
      tags:
      - health
swagger: "2.0"
